// Legal copy for screens 11–13 and the hosted web pages (web/src/pages/Legal.tsx
// renders this same file, so the store-listing URLs and the app never
// diverge). DRAFT wording written from the app's actual behaviour — have it
// reviewed by a legal professional before public launch, then update
// LEGAL_UPDATED. The entity name, ABN and address placeholders below must be
// filled in from the client's details.

export interface LegalSection {
  heading: string;
  body: string;
}

export const LEGAL_UPDATED = '13 September 2026';

// TODO(client): legal entity, ABN and address for the Terms and the Privacy
// policy.
const ENTITY = 'Investigations Differently';

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: '1 · About these terms',
    body:
      `These terms govern the use of the Event Insight app and website, provided by ${ENTITY} ("we", "us"). By creating an account, signing in or using the app you agree to these terms. Last updated ${LEGAL_UPDATED} (draft).`,
  },
  {
    heading: '2 · Who may use the app',
    body:
      'The app is intended for supervisors, investigators and facilitators conducting workplace event reviews. You must be at least 18, provide accurate account information, keep your sign-in credentials secure, and not share your account. We may suspend accounts that are compromised or misused.',
  },
  {
    heading: '3 · Recordings & consent',
    body:
      'The app does not capture consent for you. Before recording any interview you must obtain the informed consent of the person being interviewed, explain that the interview is recorded and transcribed and that AI services outside Australia process it, and comply with the surveillance and listening-device laws that apply in your state or territory. Do not record anyone who has not consented, and stop recording if consent is withdrawn. You are responsible for obtaining, recording and evidencing that consent, and for the lawfulness of every recording you make.',
  },
  {
    heading: '4 · AI-generated content',
    body:
      'Transcripts, insights and recommended actions are generated by artificial-intelligence services and may contain errors, omissions or mischaracterisations. They are decision-support material only — they are not advice, and they must be reviewed by a qualified person before any action is taken. Responsibility for decisions made from app output remains with you and your organisation.',
  },
  {
    heading: '5 · Your content',
    body:
      'You retain ownership of the events, recordings, transcripts, photos and reports created through the app. You grant us the rights needed to store and process that content solely to provide the service, including processing by the third-party AI services described in the Privacy policy.',
  },
  {
    heading: '6 · Plan, fees & the free first report',
    body:
      'Event Insight is a paid subscription: A$19.99 per month including GST, for one user. Every new account may generate one insight report free of charge before subscribing; after that free report, recording new interviews and generating reports require an active subscription, while everything already captured — events, transcripts and the free report — remains viewable and shareable in the app. Prices are in Australian dollars, are shown in your app store’s local currency at purchase, and may change with at least 30 days’ notice; a change takes effect from your next renewal after the notice.',
  },
  {
    heading: '7 · Billing, renewal & cancellation',
    body:
      'Subscriptions are bought in the app and billed by Apple (App Store) or Google (Google Play) to the account you used. They renew automatically every month unless cancelled at least 24 hours before the end of the current period, and are managed or cancelled through your device’s subscription settings — not through us. Access continues until the end of the period already paid for.',
  },
  {
    heading: '8 · Refunds & receipts',
    body:
      'Apple and Google are the merchants of record for all purchases: they collect the payment and GST, issue the receipt and tax invoice for every payment, and handle refunds under their own policies. We cannot issue separate tax invoices or process refunds for store purchases. Nothing in these terms limits your rights under the Australian Consumer Law.',
  },
  {
    heading: '9 · Deleting your account',
    body:
      'You can delete your account from the Account tab in the app or from our website. Deleting your account permanently deletes your events, recordings, transcripts and reports. Deleting your account does not cancel your subscription — cancel it in the App Store or Google Play, or you will continue to be charged.',
  },
  {
    heading: '10 · Acceptable use',
    body:
      'You must not use the app for any unlawful purpose, attempt to access data belonging to another account, interfere with the operation of the service, or upload content that is malicious or that you do not have the right to record or share.',
  },
  {
    heading: '11 · Availability',
    body:
      'The app is designed to work offline and to sync when a connection is available, but we do not guarantee uninterrupted availability of the sync, transcription or analysis services. Keep the app updated; older versions may stop working as the service evolves.',
  },
  {
    heading: '12 · Liability',
    body:
      'Nothing in these terms excludes rights that cannot be excluded under the Australian Consumer Law. To the extent permitted by law, we exclude all other warranties, and our total liability in connection with the app is limited to resupplying the service or refunding the fees paid for the period in which the problem occurred. We are not liable for decisions made in reliance on app output, or for loss of data caused by factors outside our reasonable control.',
  },
  {
    heading: '13 · Ending use & changes',
    body:
      'You may stop using the app at any time; you control your data as described in the Privacy policy. We may update these terms from time to time, and will note the date of the current version above. Continued use after a change means you accept the updated terms. These terms are governed by the laws of Australia.',
  },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    heading: '1 · Who we are',
    body:
      `Event Insight is operated by ${ENTITY} (investigationsdifferently.com.au). This policy explains what we collect through the app and website, how it is used, where it goes, and the choices available to account holders and interview participants. Last updated ${LEGAL_UPDATED} (draft).`,
  },
  {
    heading: '2 · What we collect',
    body:
      'Account information: name, email address, job title, and whether you chose to receive our newsletter. Event records: event name, site, date, description and photos. Interview material: interviewee name and role, audio recordings, transcripts and any corrections. Generated material: AI-produced insights, recommendations and exported reports. Subscription information: your plan, its status and renewal dates, and identifiers issued by the app stores and our subscription processor; we never see or store your card number. We also keep an audit log of key actions (such as approvals) for accountability. The app does not capture a consent record — the facilitator obtains consent before recording, outside the app. We do not collect advertising identifiers or use third-party analytics. If you opted in to newsletters at sign-up (the box is ticked by default), we keep your email address and the date of that choice so we can send them; you can unsubscribe at any time from the Account tab, and every email includes an unsubscribe option.',
  },
  {
    heading: '3 · How recordings are used',
    body:
      'Recordings exist to document the interview. They are transcribed automatically, the transcript is reviewed and approved in the app, and approved transcripts are analysed to produce the event insight. Recordings and transcripts are used only to provide this service — we do not sell them, and our AI providers are not authorised by us to use them to train their models.',
  },
  {
    heading: '4 · Overseas processing & service providers',
    body:
      'Transcription and analysis are performed by AI services hosted outside Australia, in the United States (audio transcription via Together AI; analysis via Anthropic). Audio and transcript content is sent to those services for processing and the results are returned to our Australian systems. Facilitators are required to disclose this when obtaining consent to record. Subscriptions are processed by Apple and Google (in-app purchases) and reconciled by RevenueCat; these providers receive your subscription details but no interview content. Transactional email is sent through Resend.',
  },
  {
    heading: '5 · Storage & security',
    body:
      'Data is stored with our hosting provider (Supabase) in Sydney, Australia, encrypted in transit, with role-based access controls. Work captured offline is stored on your device until it syncs; the device also keeps a backup copy of each recording for seven days after the event’s report is generated, then deletes it automatically. Signing out removes the local copy of your data from the device. Access to a device is protected by its own lock screen — keep your device secured.',
  },
  {
    heading: '6 · Who can access it',
    body:
      'You can access only the events you created. Our own administrator can view events and reports across the service for support and oversight, manage the question set, and receive a notification when an event is logged. We access data only as needed to operate and support the service.',
  },
  {
    heading: '7 · Retention & deletion',
    body:
      'Audio recordings are deleted from our servers automatically as soon as the event’s report is generated; recordings for events that never produce a report are deleted after a backstop window (90 days by default). Your device keeps its copy of each recording for seven days after the report, then deletes it. Transcripts and insights are retained as the review record. You can delete your account from the app or the website: your events, transcripts and reports are deleted with it. Billing records are kept for as long as tax law requires. Interview participants may ask the organisation that interviewed them to access, correct or delete their information, and we will assist with those requests.',
  },
  {
    heading: '8 · Your rights & contact',
    body:
      'We handle personal information in accordance with the Australian Privacy Principles. You can request access to or correction of your personal information, or make a privacy complaint, by contacting support@investigationsdifferently.com.au. If you are not satisfied with our response you can complain to the Office of the Australian Information Commissioner (oaic.gov.au).',
  },
];

// Screen 11 · Help & support.
export const FAQS = [
  {
    question: 'Can I record an interview with no signal?',
    answer:
      "Yes. Events and recordings are saved on the device and upload automatically once you're back online. The transcript and insight are generated after the recordings sync.",
  },
  {
    question: 'How do I correct a transcript?',
    answer:
      'Open the interview on the Approve transcript screen and tap any answer to edit it. Your correction replaces the automatic transcript, and approving unlocks the AI analysis.',
  },
  {
    question: 'What does Event Insight cost?',
    answer:
      'Your first insight report is free. After that it’s A$19.99 a month (including GST), billed through the App Store or Google Play, cancellable any time in your device’s subscription settings. Everything you captured stays viewable even without a subscription.',
  },
  {
    question: "Who can see an event's insight?",
    answer:
      'You, and our administrator for support and oversight. Insights can be shared as a PDF from the insight screen.',
  },
  {
    question: 'How long are recordings kept?',
    answer:
      'Audio is deleted from our servers automatically once the event’s report is generated (or after a backstop window if no report is produced). Your device keeps its copy for seven days after the report, then removes it. Transcripts and insights are kept as the review record.',
  },
];

export const SUPPORT_EMAIL = 'support@investigationsdifferently.com.au';
