// Legal copy for screens 11–13 and the hosted web pages (web/src/pages/Legal.tsx
// renders this same file, so the store-listing URLs and the app never
// diverge). DRAFT wording written from the app's actual behaviour — have it
// reviewed by a legal professional before public launch, then update
// LEGAL_UPDATED. The entity name, ABN and address placeholders below must be
// filled in from the client's details.

export interface LegalSection {
  heading: string;
  body: string;
}

export const LEGAL_UPDATED = '28 August 2026';

// TODO(client): legal entity, ABN and address for the Terms, the Privacy
// policy and the Stripe tax-invoice header.
const ENTITY = 'Investigations Differently';

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: '1 · About these terms',
    body:
      `These terms govern the use of the Event Insight app and web portal, provided by ${ENTITY} ("we", "us"). By creating an account, signing in or using the app you agree to these terms on your own behalf and, where applicable, on behalf of the organisation that authorised your access. Last updated ${LEGAL_UPDATED} (draft).`,
  },
  {
    heading: '2 · Who may use the app',
    body:
      'The app is intended for supervisors, investigators and facilitators conducting workplace event reviews, and for the organisations they work for. You must be at least 18, provide accurate account information, keep your sign-in credentials secure, and not share your account. We may suspend accounts that are compromised or misused.',
  },
  {
    heading: '3 · Recordings & consent',
    body:
      'The app does not capture consent for you. Before recording any interview you must obtain the informed consent of the person being interviewed, explain that the interview is recorded and transcribed and that AI services outside Australia process it, and comply with the surveillance and listening-device laws that apply in your state or territory. Do not record anyone who has not consented, and stop recording if consent is withdrawn. You are responsible for obtaining, recording and evidencing that consent, and for the lawfulness of every recording you make.',
  },
  {
    heading: '4 · AI-generated content',
    body:
      'Transcripts, insights and recommended actions are generated by artificial-intelligence services and may contain errors, omissions or mischaracterisations. They are decision-support material only — they are not advice, and they must be reviewed by a qualified person before any action is taken. Responsibility for decisions made from app output remains with you and your organisation.',
  },
  {
    heading: '5 · Your content',
    body:
      'You (for an Individual plan) or your organisation (for an Enterprise plan) retain ownership of the events, recordings, transcripts, photos and reports created through the app. You grant us the rights needed to store and process that content solely to provide the service, including processing by the third-party AI services described in the Privacy policy.',
  },
  {
    heading: '6 · Plans, fees & free trial',
    body:
      'Event Insight is a paid subscription. Individual plan: one user, A$29.99 per month including GST, with a 7-day free trial for new subscribers (one trial per person). Enterprise plan: A$19.99 per user per month including GST, for a minimum of three seats; the supervisor who sets up the organisation occupies one seat. Prices are in Australian dollars and may change with at least 30 days’ notice; a change takes effect from your next renewal after the notice.',
  },
  {
    heading: '7 · Billing, renewal & cancellation',
    body:
      'Individual subscriptions bought in the app are billed by Apple (App Store) or Google (Google Play) to the account you used, renew automatically every month unless cancelled at least 24 hours before the end of the current period, and are managed or cancelled through your device’s subscription settings. Subscriptions bought on our website, including all Enterprise plans, are billed monthly by card through our payment processor (Stripe), renew automatically until cancelled, and can be cancelled from your online account; access continues until the end of the period already paid for. Enterprise seat changes take effect immediately and are pro-rated on the next invoice. If a payment fails, access continues for a short grace period while payment is retried, after which the subscription is suspended until it is paid.',
  },
  {
    heading: '8 · Refunds',
    body:
      'Refunds for purchases made through the App Store or Google Play are handled by Apple or Google under their own policies. For subscriptions billed by us, we do not refund partial periods after a cancellation, except where the Australian Consumer Law or another law requires it. Nothing in these terms limits your rights under the Australian Consumer Law.',
  },
  {
    heading: '9 · Tax invoices',
    body:
      `For subscriptions billed by us, a tax invoice is emailed automatically for every payment and is also available from your online account. For subscriptions bought through the App Store or Google Play, Apple or Google is the merchant of record: they collect the payment and GST and issue the receipt and tax invoice, and ${ENTITY} cannot issue a separate tax invoice for those payments.`,
  },
  {
    heading: '10 · Enterprise accounts & supervisors',
    body:
      'An Enterprise organisation is created and paid for by a supervisor, who invites team members to its seats. The supervisor can see every event, interview transcript, insight and report recorded by any member of the organisation, can add and remove members, and is responsible for the organisation’s use of the app and for ensuring members understand this visibility. Members see only their own work. When a supervisor removes a member, that member can no longer sign in and their seat is released; the events they recorded remain with the organisation. If the organisation’s subscription lapses, members cannot use the app until it is restored, but their data is retained as described in the Privacy policy.',
  },
  {
    heading: '11 · Deleting your account',
    body:
      'You can delete your account from the Account tab in the app or from our website. Deleting an Individual account permanently deletes your events, recordings, transcripts and reports. Deleting an Enterprise member’s account removes your personal details and sign-in; the events you recorded remain with your organisation, which owns them. A supervisor must cancel the organisation’s subscription before deleting their account. Deleting your account does not cancel a subscription bought through the App Store or Google Play — cancel that in the store.',
  },
  {
    heading: '12 · Acceptable use',
    body:
      'You must not use the app for any unlawful purpose, attempt to access data belonging to another organisation or account, interfere with the operation of the service, or upload content that is malicious or that you do not have the right to record or share.',
  },
  {
    heading: '13 · Availability',
    body:
      'The app is designed to work offline and to sync when a connection is available, but we do not guarantee uninterrupted availability of the sync, transcription or analysis services. Keep the app updated; older versions may stop working as the service evolves.',
  },
  {
    heading: '14 · Liability',
    body:
      'Nothing in these terms excludes rights that cannot be excluded under the Australian Consumer Law. To the extent permitted by law, we exclude all other warranties, and our total liability in connection with the app is limited to resupplying the service or refunding the fees paid for the period in which the problem occurred. We are not liable for decisions made in reliance on app output, or for loss of data caused by factors outside our reasonable control.',
  },
  {
    heading: '15 · Ending use & changes',
    body:
      'You may stop using the app at any time; you or your organisation control your data as described in the Privacy policy. We may update these terms from time to time, and will note the date of the current version above. Continued use after a change means you accept the updated terms. These terms are governed by the laws of Australia.',
  },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    heading: '1 · Who we are',
    body:
      `Event Insight is operated by ${ENTITY} (investigationsdifferently.com.au). This policy explains what we collect through the app and website, how it is used, where it goes, and the choices available to account holders and interview participants. Last updated ${LEGAL_UPDATED} (draft).`,
  },
  {
    heading: '2 · What we collect',
    body:
      'Account information: name, email address, job title, whether you chose to receive our newsletter, and — for Enterprise accounts — your organisation’s name and which organisation you belong to. Event records: event name, site, date, description and photos. Interview material: interviewee name and role, audio recordings, transcripts and any corrections. Generated material: AI-produced insights, recommendations and exported reports. Subscription information: your plan, its status and renewal dates, and identifiers issued by our payment processors; we never see or store your card number. We also keep an audit log of key actions (such as approvals, invitations and removals) for accountability. The app does not capture a consent record — the facilitator obtains consent before recording, outside the app. We do not collect advertising identifiers or use third-party analytics. If you opted in to newsletters at sign-up (the box is ticked by default), we keep your email address and the date of that choice so we can send them; you can unsubscribe at any time from the Account tab, and every email includes an unsubscribe option.',
  },
  {
    heading: '3 · How recordings are used',
    body:
      'Recordings exist to document the interview. They are transcribed automatically, the transcript is reviewed and approved in the app, and approved transcripts are analysed to produce the event insight. Recordings and transcripts are used only to provide this service — we do not sell them, and our AI providers are not authorised by us to use them to train their models.',
  },
  {
    heading: '4 · Overseas processing & service providers',
    body:
      'Transcription and analysis are performed by AI services hosted outside Australia, in the United States (audio transcription via Together AI; analysis via Anthropic). Audio and transcript content is sent to those services for processing and the results are returned to our Australian systems. Facilitators are required to disclose this when obtaining consent to record. Payments are processed by Stripe (web and Enterprise subscriptions), Apple and Google (in-app subscriptions) and RevenueCat (which reconciles in-app subscriptions); these providers receive your email address and subscription details but no interview content. Transactional email (invitations, receipts, notifications) is sent through Resend.',
  },
  {
    heading: '5 · Storage & security',
    body:
      'Data is stored with our hosting provider (Supabase) in Sydney, Australia, encrypted in transit, with role-based access controls. Work captured offline is stored on the facilitator’s device until it syncs; the device also keeps a backup copy of each recording for seven days after the event’s report is generated, then deletes it automatically. Signing out removes the local copy of your data from the device. Access to a device is protected by its own lock screen — facilitators must keep their devices secured.',
  },
  {
    heading: '6 · Who can access it',
    body:
      'An Individual account holder can access only the events they created. In an Enterprise organisation, each member can access their own events, and the organisation’s supervisor can view every member’s events, interview transcripts, insights and reports for oversight — read-only. Supervisors are told this when they set up the organisation, and members are told when they accept an invitation. Our own administrator can view events and reports across the service for support and oversight, manage the question set, and receive a notification when an event is logged. We access data only as needed to operate and support the service.',
  },
  {
    heading: '7 · Retention & deletion',
    body:
      'Audio recordings are deleted from our servers automatically as soon as the event’s report is generated; recordings for events that never produce a report are deleted after a backstop window (90 days by default). The facilitator’s device keeps its copy of each recording for seven days after the report, then deletes it. Transcripts and insights are retained as the review record. You can delete your account from the app or the website: an Individual account’s events, transcripts and reports are deleted with it; an Enterprise member’s events remain with their organisation, which owns them, and the member’s personal details are removed. Billing records are kept for as long as tax law requires. Interview participants may ask the organisation that interviewed them to access, correct or delete their information, and we will assist with those requests.',
  },
  {
    heading: '8 · Your rights & contact',
    body:
      'We handle personal information in accordance with the Australian Privacy Principles. You can request access to or correction of your personal information, or make a privacy complaint, by contacting support@investigationsdifferently.com.au. If you are not satisfied with our response you can complain to the Office of the Australian Information Commissioner (oaic.gov.au).',
  },
];

// Screen 11 · Help & support.
export const FAQS = [
  {
    question: 'Can I record an interview with no signal?',
    answer:
      "Yes. Events and recordings are saved on the device and upload automatically once you're back online. The transcript and insight are generated after the recordings sync.",
  },
  {
    question: 'How do I correct a transcript?',
    answer:
      'Open the interview on the Approve transcript screen and tap any answer to edit it. Your correction replaces the automatic transcript, and approving unlocks the AI analysis.',
  },
  {
    question: "Who can see an event's insight?",
    answer:
      'The person who logged the event and, on an Enterprise plan, their supervisor — read-only. Our administrator can also view reports for support. Insights can be shared as a PDF from the insight screen.',
  },
  {
    question: 'How do I change or cancel my subscription?',
    answer:
      'If you subscribed in the app, manage it from your device’s App Store or Google Play subscription settings (Account tab → Manage subscription). Enterprise plans and web subscriptions are managed from your online account, where you can also download tax invoices.',
  },
  {
    question: 'How long are recordings kept?',
    answer:
      'Audio is deleted from our servers automatically once the event’s report is generated (or after a backstop window if no report is produced). Your device keeps its copy for seven days after the report, then removes it. Transcripts and insights are kept as the review record.',
  },
];

export const SUPPORT_EMAIL = 'support@investigationsdifferently.com.au';
